// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Data;

namespace Restaurant.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20201103114709_SeedingDatabase")]
    partial class SeedingDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Restaurant.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Cheese Cake",
                            Description = "We sell nice sweet  cheese cakes here in our shop"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Birthday Cake",
                            Description = "We sell nice sweet  Birthday here in our shop, You are all welcome"
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Description = "This cheesecake tastes as good as it looks. The ombré effect makes a great centrepiece – your friends will never guess how easy it is to make!",
                            ImagePath = "c1.jpg",
                            ProductName = "Blackcurrant ombré cheesecake",
                            UnitPrice = 3000.0
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Description = "Perphaps is the most sweetest Cheese cake in new york! Loving it",
                            ImagePath = "c2.jpg",
                            ProductName = "My NYC cheesecake",
                            UnitPrice = 2400.0
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Description = "Frozen banoffee cheesecake is sooo nice i would recommend you get one of these, you will exactly enjoy your dinner/lunch ",
                            ImagePath = "c3.jpg",
                            ProductName = "Frozen banoffee cheesecake",
                            UnitPrice = 2700.0
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            Description = "This is a great make-ahead dessert that will definitely impress your guests!",
                            ImagePath = "c4.jpg",
                            ProductName = "Black forest frozen cheesecake",
                            UnitPrice = 2500.0
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            Description = "The best way to use frozen berries in any seasoRick Stein's blueberry tart recipe, with ground almonds and egg custard is the perfect mix of comforting and refined. The tart is really stuffed with fruit with a very light binding of egg custard.",
                            ImagePath = "c7.jpg",
                            ProductName = "Frozen berries",
                            UnitPrice = 1400.0
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            Description = "With a gorgeous nutty base, sweet coconut & vanilla topping and a strawberry drizzle, this is incredible!",
                            ImagePath = "c6.jpg",
                            ProductName = "Dairy-free coconut cheesecake",
                            UnitPrice = 3500.0
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 2,
                            Description = "Forget everything you know about 'white cake,' this recipe's a game changer: rich and velvety to the point of creaminess, heady with vanilla, and almost as fluffy as angel's food cake. The secret is virgin coconut oil, which amplifies the aroma of butter and vanilla while creaming up lighter (and whiter) than butter alone. I top it all off with silky Marshmallow Buttercream, for a cake that's beguilingly complex despite its apparent simplicity. Get the recipe for White Mountain Layer Cake with Marshmallow ButtercreamMatt Taylor-Gross",
                            ImagePath = "b1.jpg",
                            ProductName = "White Mountain Layer Cake with Marshmallow Buttercream",
                            UnitPrice = 5000.0
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 2,
                            Description = "This version of the classic NOLA dessert combines a rich buttermilk cake with both lemon curd and chocolate fillings, surrounded by a vanilla German buttercream and ganache",
                            ImagePath = "b2.jpg",
                            ProductName = "New Orleans Doberge Cake",
                            UnitPrice = 4700.0
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 2,
                            Description = "Chef Magnus Nilsson's wife likes to serve this beloved Swedish cake, similar to a fudgy American brownie, chilled, but it's just as good piping hot from the pan with a scoop of ice cream. Melting the butter in this recipe first and then stirring it with the other ingredients helps ensure that as little air as possible gets incorporated into the batter. The result: a gooey, more moist cake",
                            ImagePath = "b3.jpg",
                            ProductName = "Chocolate Cake",
                            UnitPrice = 2100.0
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 2,
                            Description = "At New York's Milk Bar, Christina Tosi makes this towering cake every spring, when sweet and tiny tristar strawberries are in season. This is by no means an everyday cake, but it's worth the work that you'll put in, and worthy of a special occasion",
                            ImagePath = "b4.jpg",
                            ProductName = "Strawberry Lemon Cake",
                            UnitPrice = 2500.0
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 2,
                            Description = "Silken white chocolate buttercream frosts a tender yellow cake layered with rich lemon curd in this recipe from the restaurant",
                            ImagePath = "b5.jpg",
                            ProductName = "Lemon Curd Layer Cake",
                            UnitPrice = 4600.0
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 2,
                            Description = "The oldest and most popular dessert at San Francisco's legendary Zuni Café, this gluten-free chocolate cake boasts a fine, tender crumb and bold chocolate flavor",
                            ImagePath = "b9.jpg",
                            ProductName = "The Best Flourless Chocolate Cake",
                            UnitPrice = 5600.0
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 2,
                            Description = "Layer nutty whole wheat crêpes with delicate honey whipped cream for a light but impressive dessert",
                            ImagePath = "b10.jpg",
                            ProductName = "Whole Wheat Mille Crêpe Cake",
                            UnitPrice = 4400.0
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 2,
                            Description = "This impressive layer cake consists of 10 thin cake layers sandwiches with an old-fashioned chocolate fudge icing.",
                            ImagePath = "b11.jpg",
                            ProductName = "Classic Smith Island Cake",
                            UnitPrice = 4000.0
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Product", b =>
                {
                    b.HasOne("Restaurant.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
